### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare-data#16]
Perhaps we should add all the logo files here?

It would be a long term backup and we can link to the various versions as required in the documentation etc.

**Comment by johannct** [comment]
Is Eve ok with the licensing? Did she release copyright? (I do not remember). It is ok to add them here perhaps, but they should never be downloaded as data by data_retrieval etc, so I presume that it supposes some work there.

**Comment by raphaelshirley** [comment]
Ève doesn't have a problem with the files being public. Although we should maybe add text saying that files should only be used for the promotion of the LePHARE code. I hadn't thought about preventing downloads so if we want to have the files backed up on GitHub we should make a separate repository. I don't really mind I just want to make sure the files are available for anyone who might want them for promoting LePHARE.
