### ISSUE TITLE
Include alloutput.txt to the registry file.

### ISSUE THREAD

**Issue by drewoldag** [lephare-photoz/lephare-data#7]

**Comment by OliviaLynn** [comment]
- Okay, I have the code in (though no unit tests yet, will be following) and it seems to generate the line in the registry as expected.
- However, in the repo transfer, the workflow lost permission to open a PR (the permission setting is on the repo level, but forced by the owner overall. The check box is now unchecked, and greyed out.)
- I’m starting to doubt whether this should happen through a PR or if we should just allow the workflow to commit it directly.
- But, for now, I’ve manually added alloutputkeys.txt and its hash at the top of the data registry

**Comment by raphaelshirley** [comment]
Just to avoid possible errors it is alloutputkeys.txt

**Comment by OliviaLynn** [comment]
Completed
